fix(workspace): attempt to fix github PR checks

diff --git a/.github/workflows/pr-checks.yaml b/.github/workflows/pr-checks.yaml
--- a/.github/workflows/pr-checks.yaml
+++ b/.github/workflows/pr-checks.yaml
@@ -39,6 +39,73 @@ jobs:
             core.setOutput('infrastructure', hasInfrastructureChanges);
 
   build-frontend:
-    needs: check-changes
-    if: ${{ needs.check-changes.outputs.frontend == 'true' }}
-    uses: ./.github/workflows/build-frontend.yaml
+    needs: [check-changes]
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - uses: actions/setup-node@v4
+        with:
+          node-version: 22.x
+      - run: npm clean-install
+        working-directory: frontend/
+        if: ${{ needs.check-changes.outputs.frontend == 'true' }}
+      - run: podman build --file containerfile .
+        working-directory: frontend/
+        if: ${{ needs.check-changes.outputs.frontend == 'true' }}
+  test-frontend:
+    needs: [check-changes]
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - uses: actions/setup-node@v4
+        with:
+          node-version: 22.x
+      - run: npm clean-install
+        working-directory: frontend/
+        if: ${{ needs.check-changes.outputs.frontend == 'true' }}
+      - run: npm run format:check
+        working-directory: frontend/
+        if: ${{ needs.check-changes.outputs.frontend == 'true' }}
+      - run: npm run lint:check
+        working-directory: frontend/
+        if: ${{ needs.check-changes.outputs.frontend == 'true' }}
+      - run: npm run test -- --coverage
+        working-directory: frontend/
+        if: ${{ needs.check-changes.outputs.frontend == 'true' }}
+      - run: npx playwright install chromium --with-deps
+        working-directory: frontend/
+        if: ${{ needs.check-changes.outputs.frontend == 'true' }}
+      - run: npm run test:e2e
+        working-directory: frontend/
+        if: ${{ needs.check-changes.outputs.frontend == 'true' }}
+
+  # -------------------- status aggregation ---------------------
+  # This job aggregates the status of all PR check jobs.
+  # Branch protection should be configured to require this job to succeed.
+  # -------------------------------------------------------------
+  pr-status-check:
+    runs-on: ubuntu-latest
+    needs: [check-changes, build-frontend, test-frontend]
+    steps:
+      - name: Aggregate job statuses
+        run: |
+          # Check each job's status.
+          # Only consider jobs that *failed* as contributing to PR failure.
+          # Skipped jobs will be ignored.
+
+          JOB_STATUSES=
+
+          if [ "${{ needs.build-frontend.result }}" == "failure" ]; then
+            JOB_STATUSES+="- build-frontend: ${{ needs.build-frontend.result }}\n"
+          fi
+          if [ "${{ needs.test-frontend.result }}" == "failure" ]; then
+            JOB_STATUSES+="- test-frontend: ${{ needs.test-frontend.result }}\n"
+          fi
+
+          if [ -n "$JOB_STATUSES" ]; then
+            echo "::error::PR checks failed due to the following job failures:"
+            echo "$JOB_STATUSES"
+            exit 1 # exit with non-zero code to fail this job and the workflow
+          fi
+
+          echo "All relevant PR checks passed!"
